services:
  postgres:
    image: postgres:13
    container_name: postgres_etl
    environment:
      POSTGRES_DB: ETL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build: .
    depends_on:
      - postgres
    container_name: etl_app
    environment:
      DB_NAME: ETL
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  postgres_data: